# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: .
    binary: puppysay   # <-- THIS ENFORCES THE CORRECT NAME
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - formats: [tar.gz]
    name_template: >-
      puppysay_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: puppysay
    repository:
      owner: neha305
      name: homebrew-tap
    commit_author:
      name: Neha Gujjari
      email: gujjarineha@gmail.com
    directory: Formula
    description: "A cute puppy that says things in your terminal."
    homepage: "https://github.com/neha305/apps"

snapcrafts:
  - name: puppysay
    summary: "A cute puppy that says things in your terminal."
    description: |
      A simple, standalone CLI tool written in Go that prints out 
      an ASCII puppy along with whatever text you pass into it.
    grade: stable
    confinement: strict
    apps:
      puppysay:
        command: puppysay